<!DOCTYPE html>
<br lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<br>

<form method="post" action="" enctype="multipart/form-data">
    <p><input type="text" name="name"></p>
    <p><input type="password" name="password"></input></p>
    <p><button type="submit" name="send" value="test">Send</button></p>
</form>
<hr>
</br></br>
<a href="/"><i class="fa fa-sign-out"></i>На сайт</a>

</body>
</html>