<?php include ROOT.'/App/Views/layouts/header_admin.phtml'; ?>
<section>
    <div class="container">
        <div class="row">
            <br/>
            <h4>Добрый день Администратор!</h4>
            <br/>
            <p>Вам доступны:</p>
            <br/>
            <ul>
                <li><a href="">Управление новостями - пока не доступны</a></li>
                <li><a href="/admin_category">Управление категориями</a></li>
                <li><a href="">Управление коментариями - пока не доступны</a></li>
            </ul>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <br/>
            <div class="breadcrumbs">
                Управление категориями
            </div>

            <a href="/cat_create/">Создать категорию<i class="fa fa-pencil-square-o"></i></a>
            <h4>Список категорий</h4>
            <br/>
            <table class="table-bordered table-responsive table">
                <tr>
                    <th>ID категории</th>
                    <th>Код категории</th>
                    <th>Название категории</th>
                    <th></th>
                </tr>
                <?php foreach($categoryList as $category): ?>
                    <tr>
                        <td><?php echo $category['cat_id']; ?></td>
                        <td><?php echo $category['cat_code']; ?></td>
                        <td><?php echo $category['cat_name']; ?></td>
                        <td><a href="/cat_update/<?php echo $category['cat_id']; ?>" title="">Редактировать<i class="fa fa-pencil-square-o"></i></a></td>
                        <td><a href="/cat_delete/<?php echo $category['cat_id']; ?>" title=>"Удалить"<i class="fa fa-times"></i></a></td>
                    </tr>
                <?php endforeach; ?>
            </table>

        </div>
    </div>

</section>

</div>
</body>
<div class="page-buffer"></div>


<footer id="footer" class="page-footer"><!--Footer-->
    <div class="footer-bottom"></div>
</footer><!--/Footer-->

</html>