<?php include ROOT.'/App/Views/layouts/header_admin.phtml'; ?>

<section>
    <div class="row">
        <h4>Удалить категорию № <?php echo $id; ?></h4>
        <br/>

        <form class="form-inline" action="" method="post">
            <table class="table-bordered table-responsive table">
                <tr>
                    <th>ID категории</th>
                    <th>Код категории</th>
                    <th>Название категории</th>
                    <th></th>
                </tr>
                    <tr>
                        <td><?php echo $categoryId['cat_id']; ?></td>
                        <td><?php echo $categoryId['cat_code']; ?></td>
                        <td><?php echo $categoryId['cat_name']; ?></td>
                    </tr>
            </table>
            <button type="submit" class="btn btn-primary mt-2 mt-sm-0" name="submit">Удалить</button>
        </form>



        <div class="page-buffer"></div>
    </div>
</section>
</div>
</body>

<footer id="footer" class="page-footer"><!--Footer-->
    <div class="footer-bottom"></div>
</footer><!--/Footer-->
