<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Админпанель</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="\resources\css\styles.css" rel="stylesheet">
    <link href="\resources\css\font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script type="text/javascript" src="\resources\js\jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="\resources\js\common.js"></script>
    <script type="text/javascript" src="\resources\js\jquery.carousel-main.min.js"></script>
    <script type="text/javascript" src="\resources\js\jquery.carousel-content.min.js"></script>
    <script type="text/javascript" src="\resources\js\home-slider-settings.js"></script>
    <script type="text/javascript" src="\resources\js\carousel-portfolio-settings.js"></script>
    <script type="text/javascript" src="\resources\js\carousel-blog-settings.js"></script>
    <script type="text/javascript" src="\resources\js\carousel-testimonials-settings.js"></script>
    <script type="text/javascript" src="\resources\js\carousel-clients-settings.js"></script>
</head><!--/head-->

<body>
<div class="page-wrapper">

    <header id="header"><!--header-->
        <div class="header_top"><!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <h5>
                                <a href="/admin_panel"><i class="fa fa-edit"></i> Админпанель</a>
                            </h5>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="/"><i class="fa fa-sign-out"></i>На сайт</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header><!--/header_top-->